baseurl = "https://dmitrym.online"
title = "Dmitry M - Veridis Quo"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "dmitry-m-viridis-quo"

[params]
    author = "Dmitry M"
    info = "General Nerdery"
    description = "Dmitry's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "images/me.png"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "General Nerdery."

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css", "images/syntax.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/dmitrym0/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/dmitrym0/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/dmitrym/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"

[[menu.main]]
    name = "TIL"
    weight = 9
    url  = "https://til.dmitrym.online/"


[[menu.main]]
    name = "Tags"
    weight = 10
    url  = "/tags/"



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'emacs'
    tabWidth = 4
    pygmentsUseClassic=true
